name: griddle
description: Creating terminal-based UIs and games in Dart should be accessible and fun!
version: 0.5.0-alpha
homepage: https://github.com/matanlurey/griddle

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0
  neoansi: ^0.3.2+1

dev_dependencies:
  coverage: ^1.5.0
  neoargs: ^0.0.1
  neodart: ^0.1.1
  test: ^1.21.4
